# Generated by Django 5.2.3 on 2025-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas_app', '0002_remove_pelicula_genero_pelicula_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
